#!/bin/bash
echo "#define CG_GAME"
while IFS= read -r line
do
    if [[ "$line" =~ ^[[:space:]]*#include[[:space:]]+\"board.h\"[[:space:]]*$ ]]
    then
        cat ./src/engine/board.h
    elif [[ "$line" =~ ^[[:space:]]*#include[[:space:]]+\"hashmap.h\"[[:space:]]*$ ]]
    then
	cat ./src/engine/hashmap.h
    else
	echo "$line"
    fi
done < ./src/bots/ai_minimax.c
